Models/Tilausrivit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilausJärjestelmä.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilausrivit
    {
        public int TilausriviID { get; set; }
        public Nullable<int> TilausID { get; set; }
        public Nullable<int> TuoteID { get; set; }
        public Nullable<int> Maara { get; set; }
        public Nullable<decimal> Ahinta { get; set; }
    
        public virtual Tilaukset Tilaukset { get; set; }
        public virtual Tuotteet Tuotteet { get; set; }
    }
}

Controllers/TilausHallintaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using TilausJärjestelmä.Models;



namespace TilausJärjestelmä.Controllers
{
    
    [AuthFilter(RequiredLevel = 1)]
    public class TilausHallintaController : BaseController
    {
        // GET: TilausHallinta
        public ActionResult Index()
        {
            return View(TilausViewModel.GetViewModelList());
        }

        public ActionResult Tilausrivit(int id)
        {
            return PartialView(TilausRiviVM.GetViewModelList(id));
        }
        [AuthFilter(RequiredLevel = 2)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tilaukset = TilausViewModel.GetViewModelList();
            var t = tilaukset.Find(x => x.TilausID== id);
            if (t == null)
            {
                return HttpNotFound();
            }
            var rivit = TilausRiviVM.GetViewModelList((int)id);
            ViewData["Rivit"] = rivit;
            return View(t);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthFilter(RequiredLevel = 2)]
        public ActionResult DeleteConfirmed(int id)
        {
            //Haetaan ensin kaikki tilausrivit mitkä on poistettavan tilauksen alla
            var tilausrivit = from i in db.Tilausrivit
                              where i.TilausID == id
                              select i;
            //Poistetaan ensin kaikki rivit ennen kun voidaan poistaa tilaus
            foreach (var i in tilausrivit)
            {
                db.Tilausrivit.Remove(i);
            }
            //Haetaan tilaus ja poistetaan se
            Tilaukset tilaus = db.Tilaukset.Find(id);
            db.Tilaukset.Remove(tilaus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult TilauksenLuonti(TilausLuontiVM model)   //Tilauksen luonti sivulla kaikki data liikkuu tämän kautta
        {
            //Huom. Asiakashaku toiminto ei toimi kunnolla jos on useampi saman niminen asiakas
            //Etsintä tehdään nimellä eikä asiakas_id:llä!! Sama myös Tuotehaulla!!

            TilausLuontiVM.HaeAsiakkaatJaTuotteet(model, db);

            //Muutetaan generic listaks, jotta saadaan find metohdi käyttöön
            List<Asiakkaat> asiakaslista = model.asiakkaat.ToList();
            List<Tuotteet> tuotelista = model.tuotteet.ToList();

            //Haetaan tiedot jos ne on client puolelta valittu
            Tuotteet tuote = tuotelista.Find(a => a.Nimi == model.valittuTuote);
            Asiakkaat asia = asiakaslista.Find(a => a.Nimi == model.valittuAsiakas);

            //Asiakas Tiedot!
            //Jos on valittu asiakas client puolelta niin haetaan oikeat tiedot
            if (asia != null)
            {
                model.AsiakasID = asia.AsiakasID;
                model.Toimitusosoite = asia.Osoite.ToString();
                model.TilausID = TilausLuontiVM.HaeTilausnumero(db);
                model.Postitoimipaikka = asia.Postitoimipaikat.Postitoimipaikka.ToString();
                model.Postinumero = asia.Postinumero.ToString();
            }
            else
            {
                model.TyhjennäAsiakasTiedot();
            }


            //Tuote ja Tilausrivi tiedot
            //Jos on valittu tuote client puolelta niin haetaan oikeat tiedot
            if (tuote != null)
            {
                model.Tuotenmr = tuote.TuoteID;
                model.Hinta = tuote.Ahinta;
                decimal? summa = model.Hinta * model.maara;
                model.Rivisumma = summa;
            }
            else
            {
                model.TyhjennäTuoteTeidot();
            }

            //Liitä kalenteri ominaisuus jossain vaiheessa?
            //Päivämäärä hallinta
            model.ToimitusPvmLista = new List<string>();
            model.Tilauspvm = DateTime.Now.Date;
            if (model.Toimituspvm != null)
            {
                model.ToimitusAika = model.Toimituspvm.Value.Day - model.Tilauspvm.Value.Day;
            }
            //Luodaan Cache objekti, tällä pidetään kirjaa lisätyistä tilausriveistä
            Cacher listCache = new Cacher(); 
            if (model.uusirivi && model.maara > 0 && tuote != null && asia != null)
            {
                int riviId = TilausLuontiVM.HaeTilausRivi(db) + listCache.CacheLista.Count();
                listCache.CacheLista.Add(new TilausRiviVM(model.valittuTuote, model.maara, model.Rivisumma, riviId, model.Tuotenmr));
                model.uusirivi = false;
            }
            if (model.rivinpoisto)
            {
                listCache.PoistaRivi((int)model.PoistoIndexi);
                model.rivinpoisto = false;
            }
            if (model.tyhjennäKaikkiRivit)
            {
                listCache.TyhjennäLista();
                model.tyhjennäKaikkiRivit = false;
            }
            //Liitetään aktiiviset rivit listaan web memory cachen tiedot
            model.aktiivisetRivit = listCache.CacheLista;


            model.KokonaisSumma = model.aktiivisetRivit.Sum(x => x.Ahinta);

            //Katsotaan onko action linjastosta tullut error flag
            if (model.error)
            {
                ModelState.AddModelError("Error", "Tilauksen tallentaminen ei onnistunut, ei tarpeeksi tietoja");
                model.error = false;
            }

            return View(model);
        }

        public ActionResult Plus(TilausLuontiVM model) //Jos painetaan Plus näppäintä niin dataflow tän actionin kautta
        {
            model.maara += 1;
            return RedirectToAction("TilauksenLuonti", model);
        }
        public ActionResult Minus(TilausLuontiVM model) //Jos painetaan Miinus näppäintä niin dataflow tän actionin kautta
        {
            if (model.maara > 0)
            {
                model.maara -= 1;
            }
            return RedirectToAction("TilauksenLuonti", model);
        }
        [HttpPost]
        public ActionResult MaaranMuutos(TilausLuontiVM model, string maarax) //Jos muutetaan käsin rivin tuotemäärää ni tän actionin kautta
        {
            if (Checker.IsNumeric(maarax))
            {
                model.maara = int.Parse(maarax);
            }
            else
            {
                model.maara = 0;
            }
            return RedirectToAction("TilauksenLuonti", model);
        }
        public ActionResult LisaaRivi(TilausLuontiVM model) //Hoitaa lisää rivi buttonin toiminnon
        {
            model.uusirivi = true;
            return RedirectToAction("TilauksenLuonti", model);
        }

        public ActionResult PoistaRivi(TilausLuontiVM model) //Hoitaa poistarivi buttonin toiminnon
        {
            model.rivinpoisto = true;
            return RedirectToAction("TilauksenLuonti", model);
        }

        public ActionResult TyhjennäRivit(TilausLuontiVM model) //Hoitaa tyhjennä rivit buttonin toiminnon
        {
            model.tyhjennäKaikkiRivit = true;
            return RedirectToAction("TilauksenLuonti", model);
        }

        [HttpPost]
        public ActionResult AsiakaValinta(TilausLuontiVM model) //Kiertää tätä kautta asiakkaan dropdowboxin valinnan yhteydessä
        {

            return RedirectToAction("TilauksenLuonti", model);
        }
        [HttpPost]
        public ActionResult TuoteValinta(TilausLuontiVM model) //Kiertää tätä kautta tuotteen dropdowboxin valinnan yhteydessä
        {
            return RedirectToAction("TilauksenLuonti", model);
        }
        [HttpPost]
        public ActionResult ToimitusPvmValinta(TilausLuontiVM model) //Kiertää tätä kautta Toimituspäivä dropdowboxin valinnan yhteydessä
        {
            model.Toimituspvm = DateTime.Parse(model.ToimitusPaivastring);
            return RedirectToAction("TilauksenLuonti", model);
        }
        public ActionResult TallennaTilaus(TilausLuontiVM model)
        {
            Cacher listCache = new Cacher();
            if (String.IsNullOrEmpty(model.valittuAsiakas) || String.IsNullOrEmpty(model.valittuTuote) || listCache.CacheLista.Count() == 0
                || model.Toimituspvm == null)
            {
                //Heittää takaisin TilauksenLuonti actioniin ja merkkaa errorin
                model.error = true;
                return RedirectToAction("TilauksenLuonti", model);
            }
            Tilaukset uusitilaus = new Tilaukset()
            {
                TilausID = (int)model.TilausID,
                AsiakasID = model.AsiakasID,
                Toimitusosoite = model.Toimitusosoite,
                Postinumero = model.Postinumero,
                Tilauspvm = model.Tilauspvm,
                Toimituspvm = model.Toimituspvm
            };

            db.Tilaukset.Add(uusitilaus);

            foreach (var i in listCache.CacheLista)
            {
                Tilausrivit rivi = new Tilausrivit()
                {
                    TilausriviID = (int)i.TilausriviID,
                    TilausID = model.TilausID,
                    TuoteID = i.TuoteID,
                    Maara = i.maara,
                    Ahinta = i.Ahinta
                };
                db.Tilausrivit.Add(rivi);
            }
            db.SaveChanges();
            listCache.TyhjennäLista();
            return RedirectToAction("Index");
        }

        public ActionResult TyhjennäTiedot(TilausLuontiVM model)
        {
            Cacher listCache = new Cacher();
            listCache.TyhjennäLista();
            model.valittuAsiakas = null;
            model.valittuTuote = null;
            model.Toimituspvm = null;
            model.ToimitusPaivastring = null;

Views/TilausHallinta/Delete.cshtml
@model TilausJärjestelmä.Models.TilausViewModel

@{
    ViewBag.Title = "Delete";
}

<div class="d-flex justify-content-between">
    <h2>Poista Tilaus</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color col-12" style="width: 300px">
            <input type="submit" value="Poista" name="Delete" class="btn btn-primary col-5" />
            <a class="btn btn-secondary col-5" href="~/TilausHallinta/Index">Takaisin</a>
        </div>
    }
</div>


<h3>Haluatko varmasti poistaa tämän tilauksen?</h3>
<div class="d-flex">
    <hr />
    <dl class="d-lg-table-cell" style="margin:0px 25px 0px 0px; height: 260px">
        <dt>
            @Html.DisplayNameFor(model => model.Asiakas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Asiakas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hinta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hinta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Toimitusosoite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Toimitusosoite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Postinumero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Postinumero)
        </dd>
    </dl>
    <dl class="d-lg-table-cell" style="margin: 0px 25px 0px 0px; height: 260px">
        <dt>
            @Html.DisplayNameFor(model => model.Postitoimipaikka)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Postitoimipaikka)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tilauspvm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tilauspvm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Toimituspvm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Toimituspvm)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TilausID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TilausID)
        </dd>

    </dl>

    <table class="table">
        <tr>
            <th>
                Tuote
            </th>
            <th>
                Määrä
            </th>
            <th>
                Ahinta
            </th>
            <th>
                TilausriviID
            </th>
        </tr>

        @foreach (var item in ViewData["Rivit"] as List<TilausJärjestelmä.Models.TilausRiviVM>)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Tuote)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.maara)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ahinta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TilausriviID)
                </td>
            </tr>
        }

    </table>


</div>
<br />

Views/TilausHallinta/Index.cshtml
@model IEnumerable<TilausJärjestelmä.Models.TilausViewModel>

@{
    ViewBag.Title = "Index";
}



<div class="d-flex">
    <h2>Tilaukset</h2>
    <a class="btn btn-secondary my-2 my-sm-2" href="~/TilausHallinta/TilauksenLuonti" style="margin-left: 80%">Luo Uusi Tilaus</a>
</div>
<br />

@{
    int i = 0;
}

@foreach (var item in Model)
{

    string heading = "heading" + i.ToString();
    string collapseId = "collapse" + i.ToString();
    string parrent = "parrent" + i.ToString();
    <div class="accordion" id="@parrent">
        <div class="accordion-item">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#@collapseId" aria-expanded="false" aria-controls="@collapseId">

                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Asiakas)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Hinta)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Toimitusosoite)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Postinumero)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Postitoimipaikka)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Tilauspvm)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Toimituspvm)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TilausID)
                            </th>
                        </tr>
                    </thead>
                    <tbody style="color: green">
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Asiakas)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Hinta)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Toimitusosoite)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Postinumero)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Postitoimipaikka)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tilauspvm)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Toimituspvm)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TilausID)
                            </td>
                        </tr>
                    </tbody>
                </table>

            </button>

            <div id="@collapseId" class="accordion-collapse collapse" aria-labelledby="@heading" data-bs-parent="#@parrent" style="">
                <div class="accordion-body">
                    @Html.Action("Tilausrivit", new { id = item.TilausID })
                    <a class="btn btn-secondary col-12" @Html.ActionLink("Poista Tilaus", "Delete", new { id = item.TilausID })
                </div>
            </div>
        </div>


    </div>
    i++;
}

Views/TilausHallinta/TilauksenLuonti.cshtml
@model TilausJärjestelmä.Models.TilausLuontiVM

@{
    ViewBag.Title = "Tilauksen Luonti";
}
<div class="d-flex justify-content-between" style="height: 40px">
    <h2 class="col-4">Tilauksen Luonti</h2>
    @Html.ValidationMessage("Error", new { @class = "text-danger" })
    <a class="btn btn-primary col-1" href="~/TilausHallinta/Takaisin">Takaisin</a>
</div>


@*------------RIVI 1---------------*@
<div class="row">
    <div class="col-2">
        @using (Html.BeginForm("AsiakaValinta", "TilausHallinta", Model, FormMethod.Post))
        {
            <label class="form-label mt-4">Asiakas</label>
            @Html.DropDownListFor(x => x.valittuAsiakas, new SelectList(Model.asiakkaat.Select(s => s.Nimi)),
           "Valitse asiakas", new { @class = "form-select", onchange = "this.form.submit()" })
        }
    </div>

    <div class="col-2">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput0">Asiakas.nmr</label>
            <input class="form-control" id="disabledInput0" type="text" value="@Model.AsiakasID" placeholder="" disabled="">
        </fieldset>
    </div>

    <div class="col-2">
        @using (Html.BeginForm("TuoteValinta", "TilausHallinta", Model, FormMethod.Post))
        {
            <label class="form-label mt-4">Tuote</label>
            @Html.DropDownListFor(x => x.valittuTuote, new SelectList(Model.tuotteet.Select(s => s.Nimi)),
           "Valitse Tuote", new { @class = "form-select", onchange = "this.form.submit()" })
        }
    </div>

    <div class="col-1">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput001">Tuote.nmr</label>
            <input class="form-control" id="disabledInput001" type="text" value="@Model.Tuotenmr" placeholder="" disabled="">
        </fieldset>
    </div>

    <div class="col-1">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput002">Hinta</label>
            <input class="form-control" id="disabledInput002" type="text" value="@Model.Hinta" placeholder="" disabled="">
        </fieldset>
    </div>

    <div class="col-1">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput003">Summa</label>
            <input class="form-control" id="disabledInput003" type="text" value="@Model.Rivisumma" placeholder="" disabled="">
        </fieldset>
    </div>

</div>

@*------------RIVI 2---------------*@
<div class="row">
    <div class="col-2">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput1">Toimitus osoite</label>
            <input class="form-control" id="disabledInput1" type="text" value="@Model.Toimitusosoite" placeholder="" disabled="">
        </fieldset>
    </div>

    <div class="col-2">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput2">Tilaus.nmr</label>
            <input class="form-control" id="disabledInput2" type="text" value="@Model.TilausID" placeholder="" disabled="">
        </fieldset>
    </div>

    <div class="col-2">
        <label class="form-label mt-4">Määrä</label>
        <div class="d-flex">
            <form class="d-flex col-3">
                <a class="btn btn-light col-12" @Html.ActionLink("-", "Minus", Model)
            </form>

            @using (Html.BeginForm("MaaranMuutos", "TilausHallinta", Model, FormMethod.Post ,new {@class = "d-flex col-6"}))
            {
                <input class="form-control" type="text" name="maarax" value="@Model.maara" />
            }

            <form class="d-flex col-3">
                <a class="btn btn-light col-12" @Html.ActionLink("+", "Plus", Model)
            </form>
        </div>


    </div>

    <div class="col-sm-2" style="margin: 56px 0px 0px 0px">
        <a class="btn btn-secondary col-12" @Html.ActionLink("Lisää Rivi", "LisaaRivi", Model)
    </div>

    <div class="col-sm-2" style="margin: 56px 0px 0px 0px">
        <a class="btn btn-secondary col-12" @Html.ActionLink("Tyhjennä Rivit", "TyhjennäRivit", Model)
    </div>

</div>

@*------------RIVI 3---------------*@

<div class="row" style="height: 100px">
    <div class="col-2">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput3">Postitoimipaikka</label>
            <input class="form-control" id="disabledInput3" type="text" value="@Model.Postitoimipaikka" placeholder="" disabled="">
        </fieldset>
    </div>
    <div class="col-2">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput4">Postinumero</label>
            <input class="form-control" id="disabledInput4" type="text" value="@Model.Postinumero" placeholder="" disabled="">
        </fieldset>
    </div>
    <div class="col-8">
        <label class="form-label mt-4" for="disabledInput03">Tilausrivit</label>
        <table class="table">
            <tr>
                <th>
                    Tuote
                </th>
                <th>
                    Määrä
                </th>
                <th>
                    Ahinta
                </th>
                <th>
                    TilausriviID
                </th>
                <th> </th>
            </tr>
            @for (int i = 0; i < Model.aktiivisetRivit.Count(); i++)
            {
                <tr class="col-1">
                    <td>
                        @Model.aktiivisetRivit[i].Tuote
                    </td>
                    <td>
                        @Model.aktiivisetRivit[i].maara
                    </td>
                    <td>
                        @Model.aktiivisetRivit[i].Ahinta
                    </td>
                    <td>
                        @Model.aktiivisetRivit[i].TilausriviID
                    </td>
                    <td>
                        @{Model.PoistoIndexi = i; }
                        <a class="btn btn-secondary col-12" @Html.ActionLink("Poista", "PoistaRivi", Model)
                    </td>
                </tr>
            }

        </table>

    </div>

</div>


@*------------RIVI 4---------------*@
<div class="row">
    <div class="col-2">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput5">Tilaus.Pvm</label>
            <input class="form-control" id="disabledInput5" type="text" value="@Model.Tilauspvm" placeholder="" disabled="">
        </fieldset>
    </div>
    <div class="col-2">
        @using (Html.BeginForm("ToimitusPvmValinta", "TilausHallinta", Model, FormMethod.Post))
        {
            <label class="form-label mt-4">Toimituspvm</label>
            @Html.DropDownListFor(x => x.ToimitusPaivastring, new SelectList(Model.ToimitusPvmLista),
           "Valitse Pvm", new { @class = "form-select", onchange = "this.form.submit()" })
        }
    </div>
</div>

@*------------RIVI 5---------------*@
<div class="row">
    <div class="col-2">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput5">Toimitus aika</label>
            <input class="form-control" id="disabledInput5" type="text" value="@Model.ToimitusAika" placeholder="" disabled="">
        </fieldset>
    </div>
    <div class="col-2">
        <fieldset disabled="">
            <label class="form-label mt-4" for="disabledInput5">Kokonais summa</label>
            <input class="form-control" id="disabledInput5" type="text" value="@Model.KokonaisSumma" placeholder="" disabled="">
        </fieldset>
    </div>
</div>

@*------------RIVI 6---------------*@
<div class="row">
    <div class="col-2" style="margin: 56px 0px 0px 0px">
        <a class="btn btn-secondary col-12" @Html.ActionLink("Tyhjennä Tiedot", "TyhjennäTiedot", Model)
    </div>
    <div class="col-2" style="margin: 56px 0px 0px 0px">
        <a class="btn btn-primary col-12" @Html.ActionLink("Tallenna Tilaus", "TallennaTilaus", Model)
           
    </div>
</div>

Views/TilausHallinta/Tilausrivit.cshtml
@model IEnumerable<TilausJärjestelmä.Models.TilausRiviVM>

@{
    ViewBag.Title = "Tilausrivit";
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tuote)
        </th>
        <th>
            Määrä
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ahinta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TilausriviID)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tuote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.maara)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ahinta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TilausriviID)
            </td>

        </tr>
    }

</table>

Views/TilausHallinta/_TilausChart.cshtml
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://code.jquery.com/jquery-1.10.0.min.js"
        integrity="sha256-2+LznWeWgL7AJ1ciaIG5rFP7GKemzzl+K75tRyTByOE="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $("#Viesti").modal('show');
    });
</script>
@section scripts
{
    <script>
        const ctx = document.getElementById('myChart');

        new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                datasets: [{
                    label: '# of Votes',
                    data: [12, 19, 3, 5, 2, 3],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>


}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <canvas id="myChart"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="myChart2"></canvas>
        </div>
    </div>
</div>