Controllers/KayttajienHallintasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TilausJärjestelmä.Models;

namespace TilausJärjestelmä.Controllers
{
    [AuthFilter(RequiredLevel = 3)]
    public class KayttajienHallintasController : BaseController
    {

        // GET: KayttajienHallintas
        public ActionResult Index()
        {
            return View(LoginsVM.GetUserList(Convert.ToString(Session["UserName"])));
        }

        // GET: KayttajienHallintas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KayttajienHallintas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName,PassWord,Level")] Logins logins)
        {
            logins.LoginId = LoginsVM.GetLoginId(db);
            var log = from i in db.Logins
                      where i.UserName == logins.UserName
                      select i;

            if (log.Any())
            {
                ModelState.AddModelError("UserName", "Käyttäjätunnus on jo olemassa");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.Logins.Add(logins);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(logins);
        }

        // GET: KayttajienHallintas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Logins logins = db.Logins.Find(id);
            if (logins == null)
            {
                return HttpNotFound();
            }
            return View(logins);
        }

        // POST: KayttajienHallintas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LoginId,UserName,PassWord,Level")] Logins logins)
        {


            if (ModelState.IsValid)
            {
                db.Entry(logins).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(logins);
        }

        // GET: KayttajienHallintas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Logins logins = db.Logins.Find(id);
            if (logins == null)
            {
                return HttpNotFound();
            }
            return View(logins);
        }

        // POST: KayttajienHallintas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Logins logins = db.Logins.Find(id);
            db.Logins.Remove(logins);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [AuthFilter(RequiredLevel = 1)]
        public ActionResult SalasananVaihto(string eka, string toka)
        {
            if ((string.IsNullOrEmpty(eka) || string.IsNullOrEmpty(toka)) || eka != toka)
            {
                return View();
            }
            string test = Convert.ToString(Session["UserName"]);

            var kayttajat = from i in db.Logins
                            select i;

            var k = kayttajat.ToList();

            Logins l = k.Find(x => x.UserName == test);
            l.PassWord = eka;

            db.Entry(l).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", "TilausHallinta");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/KayttajienHallintas/Create.cshtml
@model TilausJärjestelmä.Models.Logins

@{
    ViewBag.Title = "Create";
}

<script src="https://code.jquery.com/jquery-1.10.0.min.js"
        integrity="sha256-2+LznWeWgL7AJ1ciaIG5rFP7GKemzzl+K75tRyTByOE="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $("#nappi0").click(function () {
            if ($('#lvl0').val() == 3) {
                $("#Varoitus0").modal('show');
            }
            else {
                $("#myForm1").submit();
            }
        })
    });
</script>

<h2>Uuden käyttäjän luominen</h2>

@using (Html.BeginForm("Create", "KayttajienHallintas", FormMethod.Post, new { @id = "myForm1" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Käyttäjätunnus", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Salasana", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassWord, new
           {
               htmlAttributes = new
               {
                   @class = "form-control",
                   @readonly = "",
                   @Value = "1234"

               }
           })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Turvallisuus taso", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Level, new { htmlAttributes = new { @class = "form-control", id = "lvl0", min = 1, max = 3 } })
                @Html.ValidationMessageFor(model => model.Level, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="modal fade" id="Varoitus0">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Haluatko varmasti antaa tälle käyttäjälle pääkäyttäjän oikeudet?</h2>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>

                <div class="modal-body">
                    <input class="btn btn-primary col-4" type="submit" value="Kyllä">
                    <a class="btn btn-secondary col-4" @Html.ActionLink("Takaisin", "Create")
                </div>

            </div>
        </div>
    </div>
}
<br />
<div>
    <button class="btn btn-primary my-2 my-sm-0" type="button" id="nappi0">Luo uusi käyttäjä</button>
    <a class="btn btn-secondary my-2 my-sm-0" @Html.ActionLink("Takaisin", "Index")
</div>

Views/KayttajienHallintas/Delete.cshtml
@model TilausJärjestelmä.Models.Logins

@{
    ViewBag.Title = "Delete";
}
<script src="https://code.jquery.com/jquery-1.10.0.min.js"
        integrity="sha256-2+LznWeWgL7AJ1ciaIG5rFP7GKemzzl+K75tRyTByOE="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $("#nappi").click(function () {
            $("#Varoitus").modal('show');
        })
    });
</script>

<h2>Käyttäjän poistaminen</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Käyttjänimi")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayName("Turvallisuus taso")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Level)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <button class="btn btn-primary my-2 my-sm-0" type="button" id="nappi">Poista käyttäjä</button>
    <a class="btn btn-secondary my-2 my-sm-0" @Html.ActionLink("Takaisin", "Index")
</div>


        <div class="modal fade" id="Varoitus">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title">Haluatko varmasti poistaa tämän käyttäjän?</h2>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true"></span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <input class="btn btn-primary col-4" type="submit" value="Kyllä">
                        <a class="btn btn-secondary col-4" @Html.ActionLink("Takaisin", "Delete")
                    </div>

                </div>
            </div>
        </div>
    }
</div>

Views/KayttajienHallintas/Edit.cshtml
@model TilausJärjestelmä.Models.Logins

@{
    ViewBag.Title = "Edit";
}
<script src="https://code.jquery.com/jquery-1.10.0.min.js"
        integrity="sha256-2+LznWeWgL7AJ1ciaIG5rFP7GKemzzl+K75tRyTByOE="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $("#nappi").click(function () {
            if ($('#lvl').val() == 3) {
                $("#Varoitus").modal('show');
            }
            else {
                $("#myForm").submit();
            }
        })
    });
</script>



<h2>Muokkaa käyttäjän tasoa</h2>

@using (Html.BeginForm("Edit", "KayttajienHallintas", FormMethod.Post, new { @id = "myForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LoginId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", @readonly = "" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Salasana", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new
                    { @class = "form-control", type = "password", @readonly = "" }})
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Level, new { htmlAttributes = new { @class = "form-control", id = "lvl", min = 1, max = 3 } })
                @Html.ValidationMessageFor(model => model.Level, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>

    <div class="modal fade" id="Varoitus">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Haluatko varmasti antaa tälle käyttäjälle pääkäyttäjän oikeudet?</h2>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>

                <div class="modal-body">
                    <input class="btn btn-primary col-4" type="submit" value="Kyllä">
                    <a class="btn btn-secondary col-4" @Html.ActionLink("Takaisin", "Edit")
                </div>

            </div>
        </div>
    </div>
}
<br />
<div>
    <button class="btn btn-primary my-2 my-sm-0" type="button" id="nappi">Tallenna</button>
    <a class="btn btn-secondary my-2 my-sm-0" @Html.ActionLink("Takaisin", "Index")
</div>

Views/KayttajienHallintas/Index.cshtml
@model IEnumerable<TilausJärjestelmä.Models.LoginsVM>

@{
    ViewBag.Title = "Index";
}



<div class="d-flex">
    <h2>Käyttäjätietojen hallinta</h2>
    <h3 style="margin-left: 50%">
        <a class="btn btn-secondary col-12" @Html.ActionLink("Uusi Käyttäjä", "Create")
    </h3>

</div>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayName("Turvallisuus taso")
        </th>
        <th>Toiminnot</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Level)
            </td>

            <td>
                <a class="btn btn-secondary my-2 my-sm-0" @Html.ActionLink("Muuta oikeuksia", "Edit", new { id = item.LoginId })
               <a class="btn btn-primary my-2 my-sm-0" @Html.ActionLink("Poista käyttäjä", "Delete", new { id = item.LoginId })
            </td>
        </tr>
    }

</table>

Views/KayttajienHallintas/SalasananVaihto.cshtml
@{
    ViewBag.Title = "SalasananVaihto";
}
<script src="https://code.jquery.com/jquery-3.6.3.js"></script>

@*<script src="https://code.jquery.com/jquery-1.10.0.min.js"
    integrity="sha256-2+LznWeWgL7AJ1ciaIG5rFP7GKemzzl+K75tRyTByOE="
    crossorigin="anonymous"></script>*@
<script>
    $(document).ready(function () {
        $("#toka0").change(function () {
            if ($("#eka0").val() === $("#toka0").val()) {
                $("#var").hide();
            }
            else {
                $("#var").show();
            }
        })
        $("#eka0").change(function () {
            if ($("#eka0").val() === $("#toka0").val()) {
                $("#var").hide();
            }
            else {
                $("#var").show();
            }
        })
        $("#tallenna").click(function () {
            if ($("#eka0").val() === $("#toka0").val()) {
                $("#Viest").modal('show');
                setTimeout(() => {
                    $("#formi").submit();
                }, 3000);
            }
        })
    });
</script>

<h2>Salasanan Vaihtaminen</h2>

<form id="formi">
    <label class="form-label mt-4">Uusi salasana</label>
    <input class="form-control me-sm-2" type="password" name="eka" id="eka0" value="">

    <label class="form-label mt-4">Toista uusi salasana</label>
    <input class="form-control me-sm-2" type="password" name="toka" id="toka0" value="">
    <p id="var" style="color: red; display: none">Salasanat eivät täsmää</p>
    <br />
    <button class="btn btn-secondary my-2 my-sm-0" id="tallenna" type="button">Muuta</button>

</form>

<div class="modal fade" id="Viest">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Salasana on muutettu!</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>
        </div>
    </div>
</div>

Views/KayttajienHallintas/_LevelVaroitus.cshtml
<script src="https://code.jquery.com/jquery-1.10.0.min.js"
        integrity="sha256-2+LznWeWgL7AJ1ciaIG5rFP7GKemzzl+K75tRyTByOE="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $("#nappi").click(function () {
            $("#Viestii").modal('show');
        })
        
    });
</script>

<div class="modal fade" id="Viestii">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Haluatko varmasti antaa tälle käyttäjälle pääkäyttäjä oikeudet?</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
            </div>

        </div>
    </div>
</div>